pool: $(AZURE_AGENT)

trigger:
  batch: true
  branches:
    include:
      - refs/tags/*
      - master

    exclude:
      - feature/*
      - bugfix/*
      - release/*

jobs:
  - job: testing
    displayName: Install dependencies and Run Tests
    steps:
      - bash: DOCKER_BUILDKIT=1 docker build --target tester .
        displayName: Test inside Docker
  - job: publish
    variables:
      tag: $(Build.BuildId)
      acr: $(acr)
      acrRepository: $(acrRepository)

    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
    dependsOn:
      - build
    displayName:  Publish to ACR
    steps:
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: $(acr)

      - task: Docker@2
        displayName: Push
        inputs:
          arguments: --target base
          command: push
          containerRegistry: $(acr)
          repository: $(acrRepository)
          tags: |
            latest
            $(tag)