[tool.poetry]
name ="local_databricks"
version = "0.1.0"
description = "Python library that provides a set of functions for handling running notebooks both locally and in Databricks using the same commands."
authors = ["Santiago Armstrong <santiagoarmstrong@gmail.com>"]


[tool.poetry.dependencies]
python = "^3.7"
structlog = "^20.0.0"
python-dotenv = "^0.19.1"
pydantic = "^1.7.3"
pyspark = "^3.3.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.5.4"
docformatter = "^1.4"
pylint = "^2.6.0"
flake8 = "3.8.4"
isort = "^5.7.0"
bandit = "^1.7.0"
black = "20.8b1"

[tool.black]
line-length = 79

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
# This could be using poetry build backend 
#[build-system]
#requires = ["poetry_core>=1.0.0"]
#build-backend = "poetry.core.masonry.api"