name: Publish to PyPI.org
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: python -m pip install --upgrade pip 
      - run: pip install poetry 
      - run: poetry config virtualenvs.create false
      - run: poetry install --no-dev --no-interaction --no-ansi
      - run: poetry build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
